### ISSUE TITLE
[BUG]FRDS转HDU类型丢失

### ISSUE THREAD

**Issue by ted423** [techmovie/easy-upload#174]
### 是否有重复的issue

- [X] 我已经检索过相关issue

### 问题描述

![image](https://user-images.githubusercontent.com/7042766/158507584-5d753941-24fe-470f-ae1f-fae76ebdc21f.png)

转到HDU丢失分类，从猫转过去正常
转到别的站也正常

### 期待表现

正常显示

### 运行环境

```markdown
- 浏览器名称：edge
- 浏览器版本：99.0.1150.39
- 所用用户脚本扩展名称：Tampermonkey 
- easy-upload版本：3.1.7
```

**Comment by ted423** [comment]
看url里已经把分类传过去了

**Comment by techmovie** [comment]
没这个站的号，看下是不是站点这里改了

```
map:
    movie: '401'
    tv: '402'
    tvPack: '402'
    documentary: '404'
    concert: '406'
    sport: '407'
    cartoon: '405'
    variety: '403'
```
