### ISSUE TITLE
[新站点]/carpt

### ISSUE THREAD

**Issue by pizidian** [techmovie/easy-upload#321]
### 站点地址

https://carpt.net/

### 站点架构

NexusPHP

### 站点配置
```yaml
file:
  selector: input[name="file"]
  type: file
name:
  selector: input[name="name"]
  type: text
small_descr:
  selector: input[name="small_descr"]
  type: text
url: https://carpt.net
pt_gen:
  selector: input[name="pt_gen"]
  type: text
nfo:
  selector: input[name="nfo"]
  type: file
b:
  selector: input[name="b"]
  type: button
i:
  selector: input[name="i"]
  type: button
u:
  selector: input[name="u"]
  type: button
IMG:
  selector: input[name="IMG"]
  type: button
list:
  selector: input[name="list"]
  type: button
quote:
  selector: input[name="quote"]
  type: button
tagcount:
  selector: input[name="tagcount"]
  type: button
color:
  selector: select[name="color"]
  options:
    - value: "0"
      text: --- 颜色 ---
    - value: Black
      text: Black
    - value: Sienna
      text: Sienna
    - value: DarkOliveGreen
      text: Dark Olive Green
    - value: DarkGreen
      text: Dark Green
    - value: DarkSlateBlue
      text: Dark Slate Blue
    - value: Navy
      text: Navy
    - value: Indigo
      text: Indigo
    - value: DarkSlateGray
      text: Dark Slate Gray
    - value: DarkRed
      text: Dark Red
    - value: DarkOrange
      text: Dark Orange
    - value: Olive
      text: Olive
    - value: Green
      text: Green
    - value: Teal
      text: Teal
    - value: Blue
      text: Blue
    - value: SlateGray
      text: Slate Gray
    - value: DimGray
      text: Dim Gray
    - value: Red
      text: Red
    - value: SandyBrown
      text: Sandy Brown
    - value: YellowGreen
      text: Yellow Green
    - value: SeaGreen
      text: Sea Green
    - value: MediumTurquoise
      text: Medium Turquoise
    - value: RoyalBlue
      text: Royal Blue
    - value: Purple
      text: Purple
    - value: Gray
      text: Gray
    - value: Magenta
      text: Magenta
    - value: Orange
      text: Orange
    - value: Yellow
      text: Yellow
    - value: Lime
      text: Lime
    - value: Cyan
      text: Cyan
    - value: DeepSkyBlue
      text: Deep Sky Blue
    - value: DarkOrchid
      text: Dark Orchid
    - value: Silver
      text: Silver
    - value: Pink
      text: Pink
    - value: Wheat
      text: Wheat
    - value: LemonChiffon
      text: Lemon Chiffon
    - value: PaleGreen
      text: Pale Green
    - value: PaleTurquoise
      text: Pale Turquoise
    - value: LightBlue
      text: Light Blue
    - value: Plum
      text: Plum
    - value: White
      text: White
font:
  selector: select[name="font"]
  options:
    - value: "0"
      text: --- 字体 ---
    - value: Arial
      text: Arial
    - value: Arial Black
      text: Arial Black
    - value: Arial Narrow
      text: Arial Narrow
    - value: Book Antiqua
      text: Book Antiqua
    - value: Century Gothic
      text: Century Gothic
    - value: Comic Sans MS
      text: Comic Sans MS
    - value: Courier New
      text: Courier New
    - value: Fixedsys
      text: Fixedsys
    - value: Garamond
      text: Garamond
    - value: Georgia
      text: Georgia
    - value: Impact
      text: Impact
    - value: Lucida Console
      text: Lucida Console
    - value: Lucida Sans Unicode
      text: Lucida Sans Unicode
    - value: Microsoft Sans Serif
      text: Microsoft Sans Serif
    - value: Palatino Linotype
      text: Palatino Linotype
    - value: System
      text: System
    - value: Tahoma
      text: Tahoma
    - value: Times New Roman
      text: Times New Roman
    - value: Trebuchet MS
      text: Trebuchet MS
    - value: Verdana
      text: Verdana
size:
  selector: select[name="size"]
  options:
    - value: "0"
      text: --- 字号 ---
    - value: "1"
      text: "1"
    - value: "2"
      text: "2"
    - value: "3"
      text: "3"
    - value: "4"
      text: "4"
    - value: "5"
      text: "5"
    - value: "6"
      text: "6"
    - value: "7"
      text: "7"
descr:
  selector: textarea[name="descr"]
type:
  selector: select[name="type"]
  options:
    - value: "0"
      text: 请选择
    - value: "401"
      text: 电影/Movies
    - value: "402"
      text: 连续剧/TV-Series
    - value: "403"
      text: 动漫/Animation
    - value: "404"
      text: 纪录片/Documentary
    - value: "405"
      text: 综艺/TV-Show
    - value: "406"
      text: 音乐/Music
    - value: "407"
      text: 其他/Other
"medium_sel[4]":
  selector: select[name="medium_sel[4]"]
  options:
    - value: "0"
      text: 请选择一项
    - value: "1"
      text: Encode
    - value: "2"
      text: WEB
    - value: "3"
      text: HDTV
    - value: "4"
      text: DVDRip
    - value: "5"
      text: CD
    - value: "6"
      text: Other
    - value: "7"
      text: Blu-ray
    - value: "8"
      text: Blu-rayUHD
    - value: "9"
      text: Remux
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - value: "0"
      text: 请选择一项
    - value: "1"
      text: H.264/AVC/x264
    - value: "2"
      text: H.265/HEVC/x265
    - value: "3"
      text: MPEG-2
    - value: "4"
      text: VC-1
    - value: "5"
      text: Xvid
    - value: "6"
      text: Other
"audiocodec_sel[4]":
  selector: select[name="audiocodec_sel[4]"]
  options:
    - value: "0"
      text: 请选择一项
    - value: "1"
      text: TrueHD
    - value: "2"
      text: DTS-HD/DTS
    - value: "3"
      text: AC3
    - value: "4"
      text: LPCM
    - value: "5"
      text: FLAC
    - value: "6"
      text: mp3
    - value: "7"
      text: AAC
    - value: "8"
      text: APE
    - value: "10"
      text: wav
    - value: "9"
      text: Other
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - value: "0"
      text: 请选择一项
    - value: "1"
      text: 4K_UHD
    - value: "2"
      text: 1080p/i
    - value: "3"
      text: 720p/i
    - value: "4"
      text: SD
    - value: "5"
      text: Other
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - value: "0"
      text: 请选择一项
    - value: "1"
      text: CarPT
    - value: "2"
      text: WiKi
    - value: "3"
      text: CMCT
    - value: "4"
      text: M-team
    - value: "5"
      text: Other
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
host: carpt.net
uploadPath: /upload.php

```
