### ISSUE TITLE
[新站点]请求适配PTzone

### ISSUE THREAD

**Issue by xusky0328** [techmovie/easy-upload#323]
### 站点架构

NexusPHP

### 站点配置

```yaml
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
url: https://ptzone.xyz
pt_gen:
  selector: input[name="pt_gen"]
  type: text
  label: null
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
price:
  selector: input[name="price"]
  type: number
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - value: "0"
      text: --- 颜色 ---
    - value: Black
      text: Black
    - value: Sienna
      text: Sienna
    - value: DarkOliveGreen
      text: Dark Olive Green
    - value: DarkGreen
      text: Dark Green
    - value: DarkSlateBlue
      text: Dark Slate Blue
    - value: Navy
      text: Navy
    - value: Indigo
      text: Indigo
    - value: DarkSlateGray
      text: Dark Slate Gray
    - value: DarkRed
      text: Dark Red
    - value: DarkOrange
      text: Dark Orange
    - value: Olive
      text: Olive
    - value: Green
      text: Green
    - value: Teal
      text: Teal
    - value: Blue
      text: Blue
    - value: SlateGray
      text: Slate Gray
    - value: DimGray
      text: Dim Gray
    - value: Red
      text: Red
    - value: SandyBrown
      text: Sandy Brown
    - value: YellowGreen
      text: Yellow Green
    - value: SeaGreen
      text: Sea Green
    - value: MediumTurquoise
      text: Medium Turquoise
    - value: RoyalBlue
      text: Royal Blue
    - value: Purple
      text: Purple
    - value: Gray
      text: Gray
    - value: Magenta
      text: Magenta
    - value: Orange
      text: Orange
    - value: Yellow
      text: Yellow
    - value: Lime
      text: Lime
    - value: Cyan
      text: Cyan
    - value: DeepSkyBlue
      text: Deep Sky Blue
    - value: DarkOrchid
      text: Dark Orchid
    - value: Silver
      text: Silver
    - value: Pink
      text: Pink
    - value: Wheat
      text: Wheat
    - value: LemonChiffon
      text: Lemon Chiffon
    - value: PaleGreen
      text: Pale Green
    - value: PaleTurquoise
      text: Pale Turquoise
    - value: LightBlue
      text: Light Blue
    - value: Plum
      text: Plum
    - value: White
      text: White
font:
  selector: select[name="font"]
  options:
    - value: "0"
      text: --- 字体 ---
    - value: Arial
      text: Arial
    - value: Arial Black
      text: Arial Black
    - value: Arial Narrow
      text: Arial Narrow
    - value: Book Antiqua
      text: Book Antiqua
    - value: Century Gothic
      text: Century Gothic
    - value: Comic Sans MS
      text: Comic Sans MS
    - value: Courier New
      text: Courier New
    - value: Fixedsys
      text: Fixedsys
    - value: Garamond
      text: Garamond
    - value: Georgia
      text: Georgia
    - value: Impact
      text: Impact
    - value: Lucida Console
      text: Lucida Console
    - value: Lucida Sans Unicode
      text: Lucida Sans Unicode
    - value: Microsoft Sans Serif
      text: Microsoft Sans Serif
    - value: Palatino Linotype
      text: Palatino Linotype
    - value: System
      text: System
    - value: Tahoma
      text: Tahoma
    - value: Times New Roman
      text: Times New Roman
    - value: Trebuchet MS
      text: Trebuchet MS
    - value: Verdana
      text: Verdana
size:
  selector: select[name="size"]
  options:
    - value: "0"
      text: --- 字号 ---
    - value: "1"
      text: "1"
    - value: "2"
      text: "2"
    - value: "3"
      text: "3"
    - value: "4"
      text: "4"
    - value: "5"
      text: "5"
    - value: "6"
      text: "6"
    - value: "7"
      text: "7"
descr:
  selector: textarea[name="descr"]
technical_info:
  selector: textarea[name="technical_info"]
type:
  selector: select[name="type"]
  options:
    - value: "0"
      text: 请选择
    - value: "401"
      text: Movies(电影)
    - value: "402"
      text: TV Series(电视剧)
    - value: "403"
      text: TV Shows(综艺)
    - value: "404"
      text: Documentaries(纪录片)
    - value: "405"
      text: Animations(动漫)
    - value: "406"
      text: Music(音乐)
    - value: "407"
      text: Sports(体育)
    - value: "408"
      text: Others(其它）
    - value: "410"
      text: Software(软件)
    - value: "411"
      text: Games(游戏)
    - value: "409"
      text: Others(其它）
"medium_sel[4]":
  selector: select[name="medium_sel[4]"]
  options:
    - value: "0"
      text: 请选择一项
    - value: "9"
      text: Track
    - value: "8"
      text: CD
    - value: "6"
      text: DVDR
    - value: "5"
      text: HDTV
    - value: "4"
      text: WEB-DL
    - value: "7"
      text: Encode
    - value: "3"
      text: Remux
    - value: "2"
      text: HD DVD
    - value: "1"
      text: Blu-ray
    - value: "10"
      text: UHD
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - value: "0"
      text: 请选择一项
    - value: "1"
      text: H.264
    - value: "2"
      text: VC-1
    - value: "3"
      text: MPEG-2
    - value: "4"
      text: MPEG-4
    - value: "5"
      text: Other
    - value: "6"
      text: H.265
"audiocodec_sel[4]":
  selector: select[name="audiocodec_sel[4]"]
  options:
    - value: "0"
      text: 请选择一项
    - value: "1"
      text: FLAC
    - value: "2"
      text: APE
    - value: "3"
      text: DTS
    - value: "4"
      text: MP3
    - value: "5"
      text: OGG
    - value: "6"
      text: AAC
    - value: "7"
      text: Other
    - value: "8"
      text: AC3
    - value: "9"
      text: DTS
    - value: "10"
      text: DTS-HD MA
    - value: "11"
      text: DD/AC3
    - value: "12"
      text: DDP/EAC3
    - value: "13"
      text: DTS-HD
    - value: "14"
      text: TrueHD
    - value: "15"
      text: WAV
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - value: "0"
      text: 请选择一项
    - value: "1"
      text: 1080p
    - value: "2"
      text: 1080i
    - value: "3"
      text: 720p
    - value: "4"
      text: SD
    - value: "5"
      text: 8K
    - value: "6"
      text: 4K
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - value: "0"
      text: 请选择一项
    - value: "1"
      text: HDS
    - value: "2"
      text: CHD
    - value: "3"
      text: MySiLU
    - value: "4"
      text: WiKi
    - value: "5"
      text: Other
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: HDR
pos_state:
  selector: select[name="pos_state"]
  options:
    - value: normal
      text: 普通
    - value: r_sticky
      text: 二级置顶
    - value: sticky
      text: 一级置顶
pos_state_until:
  selector: input[name="pos_state_until"]
  type: text
  label: null
picktype:
  selector: select[name="picktype"]
  options:
    - value: normal
      text: 普通
    - value: hot
      text: 热门
    - value: classic
      text: 经典
    - value: recommended
      text: 推荐
uplver:
  selector: input[name="uplver"]
  type: checkbox
  label: null
host: ptzone.xyz
uploadPath: /upload.php
```
