### ISSUE TITLE
[New Site] Bj-Share

### ISSUE THREAD

**Issue by st4rts0mething** [techmovie/easy-upload#324]
### Site based on

NexusPHP

### Site Configuration

```yaml
searchstr:
  selector: input[name="searchstr"]
  type: text
  label: null
search:
  selector: input[name="search"]
  type: text
  label: null
action:
  selector: input[name="action"]
  type: hidden
  label: null
searchuser:
  selector: input[name="searchuser"]
  type: text
  label: null
submit:
  selector: input[name="submit"]
  type: hidden
  label: null
auth:
  selector: input[name="auth"]
  type: hidden
  label: null
file_input:
  selector: input[name="file_input"]
  type: file
  label: null
type:
  selector: select[name="type"]
  options:
    - value: ""
      text:  
    - value: "13"
      text: Animes
    - value: "2"
      text: Aplicativos
    - value: "10"
      text: Audiobooks
    - value: "17"
      text: Cursos
    - value: "9"
      text: E-Books
    - value: "7"
      text: Esportes
    - value: "0"
      text: Filmes
    - value: "14"
      text: Fotos Adultas
    - value: "11"
      text: Histórias em Quadrinhos
    - value: "3"
      text: Jogos
    - value: "4"
      text: Mangás
    - value: "8"
      text: Revistas
    - value: "1"
      text: Seriados
    - value: "12"
      text: Stand Up Comedy
    - value: "6"
      text: Outros
adulto:
  selector: select[name="adulto"]
  options:
    - value: ""
      text: ""
    - value: "1"
      text: Sim
    - value: "2"
      text: Não
imdblink:
  selector: input[name="imdblink"]
  type: text
  label: null
validimdb:
  selector: input[name="validimdb"]
  type: hidden
  label: null
title:
  selector: input[name="title"]
  type: text
  label: null
titulobrasileiro:
  selector: input[name="titulobrasileiro"]
  type: text
  label: null
imdbrating:
  selector: input[name="imdbrating"]
  type: hidden
  label: null
tags:
  selector: input[name="tags"]
  type: text
  label: null
year:
  selector: input[name="year"]
  type: text
  label: null
elenco:
  selector: input[name="elenco"]
  type: text
  label: null
diretor:
  selector: input[name="diretor"]
  type: text
  label: null
duracaotipo:
  selector: input[name="duracaotipo"]
  type: text
  label: null
duracaoHR:
  selector: select[name="duracaoHR"]
  options:
    - value: "0"
      text: "0"
    - value: "1"
      text: "1"
    - value: "2"
      text: "2"
    - value: "3"
      text: "3"
    - value: "4"
      text: "4"
    - value: "5"
      text: "5"
    - value: "6"
      text: "6"
    - value: "7"
      text: "7"
    - value: "8"
      text: "8"
    - value: "9"
      text: "9"
duracaoMIN:
  selector: select[name="duracaoMIN"]
  options:
    - value: "0"
      text: "0"
    - value: "1"
      text: "1"
    - value: "2"
      text: "2"
    - value: "3"
      text: "3"
    - value: "4"
      text: "4"
    - value: "5"
      text: "5"
    - value: "6"
      text: "6"
    - value: "7"
      text: "7"
    - value: "8"
      text: "8"
    - value: "9"
      text: "9"
    - value: "10"
      text: "10"
    - value: "11"
      text: "11"
    - value: "12"
      text: "12"
    - value: "13"
      text: "13"
    - value: "14"
      text: "14"
    - value: "15"
      text: "15"
    - value: "16"
      text: "16"
    - value: "17"
      text: "17"
    - value: "18"
      text: "18"
    - value: "19"
      text: "19"
    - value: "20"
      text: "20"
    - value: "21"
      text: "21"
    - value: "22"
      text: "22"
    - value: "23"
      text: "23"
    - value: "24"
      text: "24"
    - value: "25"
      text: "25"
    - value: "26"
      text: "26"
    - value: "27"
      text: "27"
    - value: "28"
      text: "28"
    - value: "29"
      text: "29"
    - value: "30"
      text: "30"
    - value: "31"
      text: "31"
    - value: "32"
      text: "32"
    - value: "33"
      text: "33"
    - value: "34"
      text: "34"
    - value: "35"
      text: "35"
    - value: "36"
      text: "36"
    - value: "37"
      text: "37"
    - value: "38"
      text: "38"
    - value: "39"
      text: "39"
    - value: "40"
      text: "40"
    - value: "41"
      text: "41"
    - value: "42"
      text: "42"
    - value: "43"
      text: "43"
    - value: "44"
      text: "44"
    - value: "45"
      text: "45"
    - value: "46"
      text: "46"
    - value: "47"
      text: "47"
    - value: "48"
      text: "48"
    - value: "49"
      text: "49"
    - value: "50"
      text: "50"
    - value: "51"
      text: "51"
    - value: "52"
      text: "52"
    - value: "53"
      text: "53"
    - value: "54"
      text: "54"
    - value: "55"
      text: "55"
    - value: "56"
      text: "56"
    - value: "57"
      text: "57"
    - value: "58"
      text: "58"
    - value: "59"
      text: "59"
datalancamento:
  selector: input[name="datalancamento"]
  type: text
  label: null
traileryoutube:
  selector: input[name="traileryoutube"]
  type: text
  label: null
formato:
  selector: select[name="formato"]
  options:
    - value: ""
      text: ""
    - value: MKV
      text: MKV
    - value: MP4
      text: MP4
    - value: AVI
      text: AVI
    - value: ISO
      text: ISO
    - value: VOB
      text: VOB
    - value: M2TS
      text: M2TS
    - value: TS
      text: TS
    - value: Outro
      text: Outro
qualidade:
  selector: select[name="qualidade"]
  options:
    - value: ""
      text: ""
    - value: BD25
      text: BD25
    - value: BD50
      text: BD50
    - value: BD66
      text: BD66
    - value: BD100
      text: BD100
    - value: BDRip
      text: BDRip
    - value: BRRip
      text: BRRip
    - value: Blu-ray
      text: Blu-ray
    - value: DVD5
      text: DVD5
    - value: DVD9
      text: DVD9
    - value: DVDRip
      text: DVDRip
    - value: DVDScr
      text: DVDScr
    - value: HD DVD
      text: HD DVD
    - value: HDRip
      text: HDRip
    - value: HDTC
      text: HDTC
    - value: HDTV
      text: HDTV
    - value: PDTV
      text: PDTV
    - value: SDTV
      text: SDTV
    - value: TC
      text: TC
    - value: TVRip
      text: TVRip
    - value: UHDTV
      text: UHDTV
    - value: VHSRip
      text: VHSRip
    - value: WEB
      text: WEB
    - value: WEB-DL
      text: WEB-DL
    - value: WEBRip
      text: WEBRip
    - value: Outro
      text: Outro
release:
  selector: input[name="release"]
  type: text
  label: null
audio:
  selector: select[name="audio"]
  options:
    - value: ""
      text: ""
    - value: Dual Áudio
      text: Dual Áudio
    - value: Dublado
      text: Dublado
    - value: Legendado
      text: Legendado
    - value: Nacional
      text: Nacional
    - value: Sem Áudio
      text: Sem Áudio
    - value: Outro
      text: Outro
tipolegenda:
  selector: select[name="tipolegenda"]
  options:
    - value: ""
      text: ""
    - value: Embutida
      text: Embutida
    - value: Arquivos Separados
      text: Arquivos Separados
    - value: Nenhuma
      text: Nenhuma
codecvideo:
  selector: select[name="codecvideo"]
  options:
    - value: ""
      text: ""
    - value: AV1
      text: AV1
    - value: DivX
      text: DivX
    - value: H.263
      text: H.263
    - value: H.264
      text: H.264
    - value: H.265
      text: H.265
    - value: KVCD
      text: KVCD
    - value: MPEG-1
      text: MPEG-1
    - value: MPEG-2
      text: MPEG-2
    - value: RealVideo
      text: RealVideo
    - value: VC-1
      text: VC-1
    - value: VP6
      text: VP6
    - value: VP8
      text: VP8
    - value: VP9
      text: VP9
    - value: Windows Media Video
      text: Windows Media Video
    - value: XviD
      text: XviD
    - value: x264
      text: x264
    - value: x265
      text: x265
    - value: Outro
      text: Outro
codecaudio:
  selector: select[name="codecaudio"]
  options:
    - value: ""
      text: ""
    - value: AAC
      text: AAC
    - value: AC3
      text: AC3
    - value: AC3/AAC
      text: AC3/AAC
    - value: AC3/DTS
      text: AC3/DTS
    - value: AC3/E-AC-3
      text: AC3/E-AC-3
    - value: Cook
      text: Cook
    - value: DTS
      text: DTS
    - value: DTS-HD
      text: DTS-HD
    - value: DTS:X
      text: DTS:X
    - value: E-AC-3
      text: E-AC-3
    - value: FLAC
      text: FLAC
    - value: LPCM
      text: LPCM
    - value: MP1
      text: MP1
    - value: MP2
      text: MP2
    - value: MP3
      text: MP3
    - value: Opus
      text: Opus
    - value: PCM
      text: PCM
    - value: RealAudio
      text: RealAudio
    - value: TrueHD
      text: TrueHD
    - value: Vorbis
      text: Vorbis
    - value: Windows Media Audio
      text: Windows Media Audio
    - value: Outro
      text: Outro
idioma:
  selector: select[name="idioma"]
  options:
    - value: ""
      text: ""
    - value: Alemão
      text: Alemão
    - value: Árabe
      text: Árabe
    - value: Argelino
      text: Argelino
    - value: Búlgaro
      text: Búlgaro
    - value: Cantonês
      text: Cantonês
    - value: Chinês
      text: Chinês
    - value: Coreano
      text: Coreano
    - value: Croata
      text: Croata
    - value: Dinamarquês
      text: Dinamarquês
    - value: Egípcio
      text: Egípcio
    - value: Espanhol
      text: Espanhol
    - value: Estoniano
      text: Estoniano
    - value: Filipino
      text: Filipino
    - value: Finlandês
      text: Finlandês
    - value: Francês
      text: Francês
    - value: Grego
      text: Grego
    - value: Hebraico
      text: Hebraico
    - value: Hindi
      text: Hindi
    - value: Holandês
      text: Holandês
    - value: Húngaro
      text: Húngaro
    - value: Indonésio
      text: Indonésio
    - value: Inglês
      text: Inglês
    - value: Islandês
      text: Islandês
    - value: Italiano
      text: Italiano
    - value: Japonês
      text: Japonês
    - value: Macedônio
      text: Macedônio
    - value: Malaio
      text: Malaio
    - value: Marati
      text: Marati
    - value: Nigeriano
      text: Nigeriano
    - value: Norueguês
      text: Norueguês
    - value: Persa
      text: Persa
    - value: Polaco
      text: Polaco
    - value: Polonês
      text: Polonês
    - value: Português
      text: Português
    - value: Português (pt)
      text: Português (pt)
    - value: Romeno
      text: Romeno
    - value: Russo
      text: Russo
    - value: Sueco
      text: Sueco
    - value: Tailandês
      text: Tailandês
    - value: Tamil
      text: Tamil
    - value: Tcheco
      text: Tcheco
    - value: Telugo
      text: Telugo
    - value: Turco
      text: Turco
    - value: Ucraniano
      text: Ucraniano
    - value: Urdu
      text: Urdu
    - value: Vietnamita
      text: Vietnamita
    - value: Zulu
      text: Zulu
    - value: Outro
      text: Outro
remaster_title:
  selector: input[name="remaster_title"]
  type: text
  label: null
resolucaow:
  selector: input[name="resolucaow"]
  type: text
  label: null
resolucaoh:
  selector: input[name="resolucaoh"]
  type: text
  label: null
sinopse:
  selector: textarea[name="sinopse"]
fichatecnica:
  selector: textarea[name="fichatecnica"]
image:
  selector: input[name="image"]
  type: text
  label: null
screenshots:
  selector: input[name="screenshots"]
  type: hidden
  label: null
"screenshots[]":
  selector: input[name="screenshots[]"]
  type: text
  label: null
anonymous:
  selector: input[name="anonymous"]
  type: checkbox
  label: null
url: https://bj-share.info
host: bj-share.info
uploadPath: /upload.php
```
