### ISSUE TITLE
[新站点]rousi

### ISSUE THREAD

**Issue by pronii** [techmovie/easy-upload#325]
### 站点架构

NexusPHP

### 站点配置

```yaml
search:
  selector: input[name="search"]
  type: text
  label: null
search_area:
  selector: select[name="search_area"]
  options:
    - text: 标题
      value: "0"
    - text: 简介
      value: "1"
    - text: 发布者
      value: "3"
    - text: IMDB链接
      value: "4"
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
url: https://rousi.zip
pt_gen:
  selector: input[name="pt_gen"]
  type: text
  label: null
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
price:
  selector: input[name="price"]
  type: number
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 颜色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字体 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字号 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
technical_info:
  selector: textarea[name="technical_info"]
type:
  selector: select[name="type"]
  options:
    - text: 请选择
      value: "0"
    - text: Movies(电影)
      value: "401"
    - text: TV Series(电视剧)
      value: "402"
    - text: TV Shows(综艺)
      value: "403"
    - text: Sports(体育、竞技、武术及相关)
      value: "407"
    - text: Documentaries(纪录片)
      value: "404"
    - text: Games(游戏及相关)
      value: "410"
    - text: Music(音乐、专辑、MV、演唱会)
      value: "406"
    - text: Art(舞蹈、歌剧、戏曲、相声、评书等)
      value: "419"
    - text: Science(科学、知识、技能)
      value: "411"
    - text: School(应试、考级、初中以上教育)
      value: "412"
    - text: Book(书籍、杂志、报刊、有声书)
      value: "413"
    - text: Code(IT技术、建模、编程、信息技术、大数据、人工智能)
      value: "414"
    - text: Animations(3D动画、2.5次元)
      value: "405"
    - text: ACGN(二次元、漫画、动漫)
      value: "415"
    - text: Baby(婴幼、儿童、早教、小学及相关)
      value: "416"
    - text: Resource(图片、文档、素材、模板)
      value: "417"
    - text: Software(软件、系统、程序、APP等)
      value: "418"
    - text: Other(其它，确认上边无分类)
      value: "409"
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: 合集
uplver:
  selector: input[name="uplver"]
  type: checkbox
  label: null
host: rousi.zip
uploadPath: /upload.php
```
