### ISSUE TITLE
[新站点] ICC 冰淇淋

### ISSUE THREAD

**Issue by pronii** [techmovie/easy-upload#326]
### 站点架构

NexusPHP

### 站点配置

```yaml
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
url: https://www.icc2022.com
pt_gen:
  selector: input[name="pt_gen"]
  type: text
  label: null
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 颜色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字体 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字号 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
type:
  selector: select[name="type"]
  options:
    - text: 请选择
      value: "0"
    - text: 音乐
      value: "408"
    - text: 其他
      value: "409"
    - text: 体育
      value: "407"
    - text: MV
      value: "406"
    - text: 综艺
      value: "403"
    - text: 电视剧
      value: "402"
    - text: 动漫
      value: "405"
    - text: 纪录片
      value: "404"
    - text: 电影
      value: "401"
"medium_sel[4]":
  selector: select[name="medium_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Track
      value: "9"
    - text: CD
      value: "8"
    - text: DVDR
      value: "6"
    - text: HDTV
      value: "5"
    - text: MiniBD
      value: "4"
    - text: Encode
      value: "7"
    - text: Remux
      value: "3"
    - text: HD DVD
      value: "2"
    - text: Blu-ray
      value: "1"
    - text: WEB-DL
      value: "10"
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: H.264
      value: "1"
    - text: H.265
      value: "6"
    - text: VC-1
      value: "2"
    - text: Xvid
      value: "3"
    - text: MPEG-2
      value: "4"
    - text: Other
      value: "5"
    - text: HEVC
      value: "7"
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 1080p
      value: "1"
    - text: 1080i
      value: "2"
    - text: 720p
      value: "3"
    - text: SD
      value: "4"
    - text: 2K
      value: "5"
    - text: 4K
      value: "6"
    - text: 8K
      value: "7"
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: HDS
      value: "1"
    - text: CHD
      value: "2"
    - text: MySiLU
      value: "3"
    - text: WiKi
      value: "4"
    - text: Other
      value: "5"
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: 教育
uplver:
  selector: input[name="uplver"]
  type: checkbox
  label: null
host: www.icc2022.com
uploadPath: /upload.php
```
