### ISSUE TITLE
PTcafe

### ISSUE THREAD

**Issue by xingfeng305** [techmovie/easy-upload#327]
### 站点架构

NexusPHP

### 站点配置

```yaml
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
url: https://ptcafe.club
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 颜色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字体 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字号 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
technical_info:
  selector: textarea[name="technical_info"]
type:
  selector: select[name="type"]
  options:
    - text: 请选择
      value: "0"
    - text: 电影
      value: "401"
    - text: 剧集
      value: "402"
    - text: 综艺
      value: "403"
    - text: 纪录
      value: "404"
    - text: 动漫
      value: "405"
    - text: 演唱
      value: "406"
    - text: 体育
      value: "407"
    - text: 音乐
      value: "408"
    - text: 其他
      value: "409"
"source_sel[4]":
  selector: select[name="source_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 大陆
      value: "1"
    - text: 港台
      value: "2"
    - text: 欧美
      value: "3"
    - text: 日本
      value: "4"
    - text: 韩国
      value: "5"
    - text: 印度
      value: "6"
    - text: 其他
      value: "7"
"medium_sel[4]":
  selector: select[name="medium_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: UHD Blu-ray 原盘
      value: "1"
    - text: UHD Blu-ray DIY
      value: "2"
    - text: UHD Remux
      value: "3"
    - text: Blu-ray 原盘
      value: "4"
    - text: Blu-ray DIY
      value: "5"
    - text: Remux
      value: "6"
    - text: Encode
      value: "7"
    - text: WEB-DL
      value: "8"
    - text: TV
      value: "9"
    - text: DVD
      value: "10"
    - text: CD
      value: "11"
    - text: Track
      value: "12"
    - text: Other
      value: "13"
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: H.265/HEVC
      value: "1"
    - text: H.264/AVC
      value: "2"
    - text: X265
      value: "3"
    - text: X264
      value: "4"
    - text: VC-1
      value: "5"
    - text: MPEG-2
      value: "6"
    - text: MPEG-4
      value: "7"
    - text: XVID
      value: "8"
    - text: VP9
      value: "9"
    - text: DIVX
      value: "10"
    - text: Other
      value: "11"
"audiocodec_sel[4]":
  selector: select[name="audiocodec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: DTS-HDMA:X 7.1
      value: "1"
    - text: DTS-HDMA
      value: "2"
    - text: DTS-HDHR
      value: "3"
    - text: DTS-HD
      value: "4"
    - text: DTS-X
      value: "5"
    - text: LPCM
      value: "6"
    - text: AC3
      value: "7"
    - text: Atmos
      value: "8"
    - text: AAC
      value: "9"
    - text: TrueHD
      value: "10"
    - text: DTS
      value: "11"
    - text: FLAC
      value: "12"
    - text: APE
      value: "13"
    - text: MP3
      value: "14"
    - text: WAV
      value: "15"
    - text: OPUS
      value: "16"
    - text: OGG
      value: "17"
    - text: Other
      value: "18"
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 4320P/8K/FUHD
      value: "1"
    - text: 2160P/4K/UHD
      value: "2"
    - text: 1080p/1080i/FHD
      value: "3"
    - text: 720p/720i/HD
      value: "4"
    - text: 360p/360i/SD
      value: "5"
    - text: Other
      value: "6"
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: ADE
      value: "1"
    - text: ADWeb
      value: "2"
    - text: Audies
      value: "3"
    - text: beAst
      value: "4"
    - text: BeiTai
      value: "5"
    - text: BeyondHD
      value: "6"
    - text: BtsTV
      value: "7"
    - text: CafeTV
      value: "8"
    - text: CafeWEB
      value: "9"
    - text: CHDBits
      value: "10"
    - text: CHDWEB
      value: "11"
    - text: CMCT
      value: "12"
    - text: DJWEB
      value: "13"
    - text: FRDS
      value: "14"
    - text: HDCTV
      value: "15"
    - text: HDH
      value: "16"
    - text: HDHome
      value: "17"
    - text: HDSky
      value: "18"
    - text: HDSWEB
      value: "19"
    - text: HHWEB
      value: "20"
    - text: MTeam
      value: "21"
    - text: MWeb
      value: "22"
    - text: OurBits
      value: "23"
    - text: OurTV
      value: "24"
    - text: PTCafe
      value: "25"
    - text: PTerWEB
      value: "26"
    - text: QHstudIo
      value: "27"
    - text: TTG
      value: "28"
    - text: WiKi
      value: "29"
    - text: Other
      value: "30"
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: 最佳影片
host: ptcafe.club
uploadPath: /upload.php
```
