### ISSUE TITLE
[新站点]熊猫高清

### ISSUE THREAD

**Issue by 616734202** [techmovie/easy-upload#329]
### 站点架构

NexusPHP

### 站点配置

```yaml
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
url: https://pandapt.net
pt_gen:
  selector: input[name="pt_gen"]
  type: text
  label: null
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 颜色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字体 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字号 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
technical_info:
  selector: textarea[name="technical_info"]
type:
  selector: select[name="type"]
  options:
    - text: 请选择
      value: "0"
    - text: 电影
      value: "401"
    - text: 电视剧
      value: "402"
    - text: 动漫
      value: "405"
    - text: 综艺
      value: "403"
    - text: 纪录片
      value: "404"
    - text: 体育
      value: "407"
    - text: 软件
      value: "412"
    - text: 游戏
      value: "411"
    - text: 电子书
      value: "410"
    - text: 音乐短片
      value: "406"
    - text: 演唱会/音乐会
      value: "413"
    - text: 音乐
      value: "408"
    - text: 其他
      value: "409"
"medium_sel[4]":
  selector: select[name="medium_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: UHD Blu-ray
      value: "11"
    - text: Blu-ray
      value: "1"
    - text: Remux
      value: "3"
    - text: Encode
      value: "7"
    - text: Track
      value: "9"
    - text: WEB-DL
      value: "10"
    - text: CD
      value: "8"
    - text: DVDR
      value: "6"
    - text: HDTV
      value: "5"
    - text: UHDTV
      value: "12"
    - text: MiniBD
      value: "4"
    - text: HD DVD
      value: "2"
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 4320k/8K
      value: "6"
    - text: 2160p/4K
      value: "5"
    - text: 1080p
      value: "1"
    - text: 1080i
      value: "2"
    - text: 720p
      value: "3"
    - text: SD
      value: "7"
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: HEVC/H.265/x265
      value: "6"
    - text: AVC/H.264/x264
      value: "1"
    - text: VP8/VP9
      value: "7"
    - text: VC-1
      value: "2"
    - text: Xvid
      value: "3"
    - text: MPEG-2
      value: "4"
    - text: Other
      value: "5"
"audiocodec_sel[4]":
  selector: select[name="audiocodec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: AV3A
      value: "19"
    - text: TrueHD Atmos
      value: "8"
    - text: TrueHD
      value: "1"
    - text: DTS-X
      value: "2"
    - text: DTS-HD
      value: "3"
    - text: DTS-HR
      value: "18"
    - text: DTS
      value: "4"
    - text: DD/AC3
      value: "5"
    - text: DDP/EAC3
      value: "6"
    - text: AAC
      value: "7"
    - text: FLAC
      value: "11"
    - text: LPCM/PCM
      value: "9"
    - text: MP3
      value: "10"
    - text: MP2
      value: "17"
    - text: APE
      value: "12"
    - text: OGG
      value: "13"
    - text: OPUS
      value: "14"
    - text: WAV
      value: "15"
    - text: Other
      value: "16"
"source_sel[4]":
  selector: select[name="source_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: CHN(中国大陆)
      value: "7"
    - text: EU/US(欧美)
      value: "1"
    - text: HK/MAC/TW(港澳台地区)
      value: "2"
    - text: JPN(日本)
      value: "3"
    - text: KOR(韩国)
      value: "4"
    - text: IND(印度)
      value: "9"
    - text: SEA(东南亚)
      value: "8"
    - text: Other(其他)
      value: "6"
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Panda(原盘diy组)
      value: "6"
    - text: Panda(原盘Remux组)
      value: "10"
    - text: Panda(压制组)
      value: "1"
    - text: AilMWeb(流媒体组)
      value: "7"
    - text: AilMWeb(流媒体组-分集)
      value: "19"
    - text: AilMTV(电视录制组)
      value: "8"
    - text: AilMUpscale(超分视频组)
      value: "14"
    - text: CatEDU(部分禁转)
      value: "15"
    - text: Other
      value: "5"
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: 自购
approval:
  selector: input[name="approval"]
  type: checkbox
  label: null
host: pandapt.net
uploadPath: /upload.php
```
