### ISSUE TITLE
[新站点]织梦

### ISSUE THREAD

**Issue by 616734202** [techmovie/easy-upload#330]
### 站点架构

NexusPHP

### 站点配置

```yaml
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
url: https://zmpt.cc
pt_gen:
  selector: input[name="pt_gen"]
  type: text
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 颜色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字体 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字号 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
type:
  selector: select[name="type"]
  options:
    - text: 请选择
      value: "0"
    - text: 其他 / Misc
      value: "409"
    - text: 纪录片 / documentary
      value: "422"
    - text: 动漫 / Anime
      value: "417"
    - text: 短剧 / Short Play
      value: "427"
    - text: 电影 / Movies
      value: "401"
    - text: 电视剧 / TV Series
      value: "402"
    - text: 综艺 / TV Shows
      value: "403"
    - text: 音乐 / Music
      value: "423"
    - text: 有声书 / Audiobook
      value: "424"
    - text: 软件 / Software
      value: "425"
    - text: 游戏 / Game
      value: "426"
"medium_sel[4]":
  selector: select[name="medium_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 其他资料
      value: "12"
    - text: CD
      value: "8"
    - text: DVDR
      value: "6"
    - text: HDTV
      value: "5"
    - text: MiniBD
      value: "4"
    - text: Encode
      value: "7"
    - text: Remux
      value: "3"
    - text: HD DVD
      value: "2"
    - text: Blu-ray
      value: "1"
    - text: WEB-DL
      value: "10"
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 480p
      value: "7"
    - text: 720p
      value: "8"
    - text: 1080p/1080i
      value: "1"
    - text: 2K/1440p
      value: "6"
    - text: 4K/2160p
      value: "5"
    - text: 8K/4320p
      value: "9"
"audiocodec_sel[4]":
  selector: select[name="audiocodec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Other
      value: "7"
    - text: FLAC
      value: "1"
    - text: APE
      value: "2"
    - text: DTS
      value: "3"
    - text: OGG
      value: "5"
    - text: AC3
      value: "8"
    - text: AAC
      value: "6"
    - text: MP3
      value: "4"
    - text: ALAC
      value: "9"
    - text: WAV
      value: "10"
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Other
      value: "5"
    - text: ZmWeb
      value: "7"
    - text: ZmPT
      value: "6"
    - text: ZmMusic
      value: "8"
    - text: DYZ-Movie
      value: "9"
    - text: GodDramas
      value: "10"
"custom_fields[4][1]":
  selector: input[name="custom_fields[4][1]"]
  type: text
  label: null
"custom_fields[4][2]":
  selector: input[name="custom_fields[4][2]"]
  type: text
  label: null
"custom_fields[4][3]":
  selector: input[name="custom_fields[4][3]"]
  type: text
  label: null
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: 分集
uplver:
  selector: input[name="uplver"]
  type: checkbox
  label: null
host: zmpt.cc
uploadPath: /upload.php
```
