### ISSUE TITLE
[新站点]老师

### ISSUE THREAD

**Issue by 616734202** [techmovie/easy-upload#333]
### 站点架构

NexusPHP

### 站点配置

```yaml
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
url: https://www.nicept.net
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 顏色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字體 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字型大小 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
type:
  selector: select[name="type"]
  options:
    - text: 請選擇
      value: "0"
    - text: SM调教（限制级）
      value: "504"
    - text: 写真、套图
      value: "404"
    - text: 真人秀，自拍（限制级）
      value: "503"
    - text: 动漫（限制级）
      value: "403"
    - text: 其他（限制级）
      value: "501"
    - text: 欧美
      value: "402"
    - text: 日本无码
      value: "401"
    - text: 日本有码
      value: "500"
"source_sel[4]":
  selector: select[name="source_sel[4]"]
  options:
    - text: 請選擇一項
      value: "0"
    - text: Blu-ray
      value: "1"
    - text: HD DVD
      value: "2"
    - text: DVD
      value: "3"
    - text: HDTV
      value: "4"
    - text: TV
      value: "5"
    - text: Other
      value: "6"
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - text: 請選擇一項
      value: "0"
    - text: H.264
      value: "1"
    - text: VC-1
      value: "2"
    - text: Xvid
      value: "3"
    - text: MPEG-2
      value: "4"
    - text: Other
      value: "5"
    - text: HEVC
      value: "13"
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - text: 請選擇一項
      value: "0"
    - text: 720p以下
      value: "11"
    - text: 720p
      value: "3"
    - text: 1080i
      value: "2"
    - text: 1080p
      value: "1"
    - text: 4K 2160p
      value: "10"
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: HDR
uplver:
  selector: input[name="uplver"]
  type: checkbox
  label: null
host: www.nicept.net
uploadPath: /upload.php
```
