### ISSUE TITLE
[新站点]自由农场

### ISSUE THREAD

**Issue by 616734202** [techmovie/easy-upload#334]
### 站点架构

NexusPHP

### 站点配置

```yaml
search:
  selector: input[name="search"]
  type: text
  label: null
search_area:
  selector: select[name="search_area"]
  options:
    - text: 标题
      value: "0"
    - text: 简介
      value: "1"
    - text: 发布者
      value: "3"
    - text: IMDB链接
      value: "4"
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
url: https://pt.0ff.cc
pt_gen:
  selector: input[name="pt_gen"]
  type: text
  label: null
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 颜色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字体 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字号 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
technical_info:
  selector: textarea[name="technical_info"]
type:
  selector: select[name="type"]
  options:
    - text: 请选择
      value: "0"
    - text: Education|学习教育
      value: "413"
    - text: Course|网络教程
      value: "414"
    - text: book|书籍
      value: "415"
    - text: Resources|网络资源
      value: "416"
    - text: Game|游戏
      value: "417"
    - text: 待定
      value: "425"
    - text: 待定
      value: "424"
    - text: 待定
      value: "423"
    - text: 待定
      value: "422"
    - text: 待定
      value: "421"
    - text: 待定
      value: "420"
    - text: 待定
      value: "419"
    - text: 待定
      value: "418"
    - text: Others|其他
      value: "426"
"source_sel[4]":
  selector: select[name="source_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 内地 (China,CHN)
      value: "35"
    - text: 香港 (HKG,CHN)
      value: "36"
    - text: 台湾 (TWN,CHN)
      value: "37"
    - text: 韩国 (KOR)
      value: "39"
    - text: 欧美 (Western)
      value: "38"
    - text: 日本 (JPN)
      value: "40"
    - text: 印度 (IND)
      value: "41"
    - text: 其它 (Other)
      value: "42"
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 8K/4320P
      value: "1"
    - text: 4K/2160P
      value: "2"
    - text: 1080P
      value: "3"
    - text: 1440P
      value: "4"
    - text: 1080I
      value: "5"
    - text: 720P
      value: "6"
    - text: SD
      value: "7"
    - text: 其它 (Other)
      value: "14"
"medium_sel[4]":
  selector: select[name="medium_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: UHD Blu-ray
      value: "1"
    - text: Blu-ray
      value: "2"
    - text: UHDTV
      value: "3"
    - text: HDTV
      value: "4"
    - text: Remux
      value: "5"
    - text: Encode
      value: "6"
    - text: HDTV
      value: "7"
    - text: DVDR
      value: "8"
    - text: CD
      value: "9"
    - text: MiniBD
      value: "10"
    - text: Track
      value: "11"
    - text: WEB-DL
      value: "12"
    - text: SACD
      value: "13"
    - text: HD DVD
      value: "14"
    - text: 3D Blu-ray
      value: "15"
    - text: 其它 (Other)
      value: "21"
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: H.265/HEVC
      value: "1"
    - text: H.264/AVC
      value: "2"
    - text: X265
      value: "3"
    - text: X264
      value: "4"
    - text: HEVC
      value: "5"
    - text: VC-1
      value: "6"
    - text: MPEG-4
      value: "7"
    - text: MPEG-2
      value: "8"
    - text: Xvid
      value: "9"
    - text: MVC
      value: "10"
    - text: ProRes
      value: "11"
    - text: VP8/9
      value: "12"
    - text: AV1
      value: "13"
    - text: 其它 (Other)
      value: "14"
"audiocodec_sel[4]":
  selector: select[name="audiocodec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: DTS-HDMA:X 7.1
      value: "10"
    - text: 其它 (Other)
      value: "22"
    - text: OGG
      value: "21"
    - text: PCM
      value: "17"
    - text: DSD
      value: "16"
    - text: APE
      value: "15"
    - text: DTS
      value: "14"
    - text: AAC
      value: "13"
    - text: MP3
      value: "12"
    - text: WAV
      value: "11"
    - text: TrueHD Atmos
      value: "1"
    - text: FLAC
      value: "9"
    - text: OPUS
      value: "8"
    - text: LPCM
      value: "7"
    - text: DTS-X
      value: "6"
    - text: TrueHD
      value: "5"
    - text: AC3|DD
      value: "4"
    - text: DTS-HD|HR
      value: "3"
    - text: DTS-HD|MA
      value: "2"
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: FFWEB/网络视频小组
      value: "3"
    - text: FFTV/电视录制小组
      value: "6"
    - text: FFCD/无损小组
      value: "4"
    - text: 其它 (Other)
      value: "14"
    - text: 待定
      value: "11"
    - text: 待定
      value: "9"
    - text: 待定
      value: "7"
    - text: 待定
      value: "13"
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: 禁转
"codec_sel[5]":
  selector: select[name="codec_sel[5]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 学前 (preschool)
      value: "15"
    - text: 小学 (primary school)
      value: "16"
    - text: 初中 (Junior high school)
      value: "17"
    - text: 高中 (High school)
      value: "18"
    - text: 大学 (University)
      value: "19"
    - text: 考研 (Postgraduate)
      value: "20"
    - text: 外语 (Foreign Languages)
      value: "21"
    - text: 资格 (Qualifications)
      value: "22"
    - text: 技能 (Skill)
      value: "23"
    - text: 专业 (Major)
      value: "24"
    - text: 其它 (Other)
      value: "25"
"source_sel[5]":
  selector: select[name="source_sel[5]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 励志 (Lnspirational)
      value: "22"
    - text: 艺术(Art)
      value: "34"
    - text: 少儿 (A juvenile)
      value: "33"
    - text: 同人 (Fan fiction)
      value: "32"
    - text: 外文(Foreign Novels)
      value: "31"
    - text: 穿越 (Traversing)
      value: "30"
    - text: 青春 (Youth novel)
      value: "29"
    - text: 言情 (Romantic)
      value: "28"
    - text: 漫画 (Cartoon)
      value: "27"
    - text: 审美 (Aesthetic)
      value: "26"
    - text: 人文 (Humanistic)
      value: "25"
    - text: 生活 (Life)
      value: "24"
    - text: 经济 (Economic)
      value: "23"
    - text: 科幻 (Science)
      value: "20"
    - text: 体育 (Sports)
      value: "19"
    - text: 游戏 (Game)
      value: "18"
    - text: 历史 (Historical)
      value: "17"
    - text: 军事 (Military)
      value: "16"
    - text: 现实 (Realistic)
      value: "15"
    - text: 都市 (Metropolis)
      value: "14"
    - text: 仙侠 (Supernatural)
      value: "13"
    - text: 武侠 (Knight errant)
      value: "12"
    - text: 奇幻 (Fantasy)
      value: "11"
    - text: 玄幻 (Mysterious)
      value: "10"
    - text: 悬疑 (Suspense)
      value: "21"
    - text: 其它 (Other)
      value: "9"
"processing_sel[5]":
  selector: select[name="processing_sel[5]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 电子书 (e-book)
      value: "1"
    - text: 有声书 (Audio book)
      value: "2"
    - text: 图文 (Image text)
      value: "3"
    - text: 视频 (Video)
      value: "4"
    - text: 音频 (Audio)
      value: "5"
    - text: 其它 (Other)
      value: "14"
    - text: 待定
      value: "6"
    - text: 待定
      value: "7"
    - text: 待定
      value: "15"
    - text: 待定
      value: "16"
    - text: 待定
      value: "17"
"medium_sel[5]":
  selector: select[name="medium_sel[5]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Windows
      value: "24"
    - text: IOS
      value: "23"
    - text: Android
      value: "22"
    - text: AZW/AZW3
      value: "16"
    - text: EPUB
      value: "17"
    - text: MOBI
      value: "18"
    - text: PDF
      value: "19"
    - text: TXT
      value: "20"
"team_sel[5]":
  selector: select[name="team_sel[5]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: FFEDU/教育资源小组
      value: "2"
    - text: FFEB/电子书小组
      value: "1"
    - text: FFAB/有声书小组
      value: "5"
    - text: 其它 (Other)
      value: "12"
    - text: 待定
      value: "10"
    - text: 待定
      value: "8"
"tags[5][]":
  selector: input[name="tags[5][]"]
  type: checkbox
  label: 禁转
host: pt.0ff.cc
uploadPath: /upload.php
```
