### ISSUE TITLE
[新站点]铂金学院

### ISSUE THREAD

**Issue by 616734202** [techmovie/easy-upload#337]
### 站点架构

NexusPHP

### 站点配置

```yaml
search:
  selector: input[name="search"]
  type: text
  label: null
search_area:
  selector: select[name="search_area"]
  options:
    - text: 标题
      value: "0"
    - text: 简介
      value: "1"
    - text: 发布者
      value: "3"
    - text: IMDB链接
      value: "4"
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
url: https://ptchina.org
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 颜色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字体 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字号 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
technical_info:
  selector: textarea[name="technical_info"]
type:
  selector: select[name="type"]
  options:
    - text: 请选择
      value: "0"
    - text: Documentaries/纪录片
      value: "404"
    - text: TV Series/电视剧
      value: "402"
    - text: Movies/电影
      value: "401"
"medium_sel[4]":
  selector: select[name="medium_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Other
      value: "13"
    - text: HDTV
      value: "12"
    - text: WEB-DL
      value: "9"
    - text: 1080p/i压制
      value: "8"
    - text: BD Remux
      value: "7"
    - text: BD DIY
      value: "6"
    - text: BD 原盘
      value: "5"
    - text: UHD 压制
      value: "4"
    - text: UHD Remux
      value: "3"
    - text: UHD DIY
      value: "2"
    - text: UHD原盘
      value: "1"
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Other
      value: "15"
    - text: AV1
      value: "14"
    - text: MPEG-4
      value: "12"
    - text: Xvid
      value: "13"
    - text: MPEG-2
      value: "11"
    - text: VC-1
      value: "5"
    - text: X265
      value: "4"
    - text: H.265/HEVC
      value: "3"
    - text: x264
      value: "2"
    - text: H.264/AVC
      value: "1"
"audiocodec_sel[4]":
  selector: select[name="audiocodec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Other
      value: "24"
    - text: MP3
      value: "23"
    - text: WAV
      value: "22"
    - text: APE
      value: "21"
    - text: FLAC
      value: "20"
    - text: AAC
      value: "19"
    - text: AC3
      value: "18"
    - text: DDP/DD+
      value: "17"
    - text: DDP/DD+/EAC3
      value: "16"
    - text: DDP Atmos
      value: "15"
    - text: LPCM
      value: "7"
    - text: True-HD
      value: "6"
    - text: DTS-HD HR
      value: "5"
    - text: DTS-HDMA
      value: "4"
    - text: DTS X
      value: "3"
    - text: DTS
      value: "2"
    - text: TrueHD Atmos
      value: "1"
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Other
      value: "6"
    - text: 1080i
      value: "4"
    - text: 1080p
      value: "3"
    - text: 2K/1440p
      value: "2"
    - text: 4K/UHD/2160P
      value: "1"
"processing_sel[4]":
  selector: select[name="processing_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Other
      value: "12"
    - text: EU/欧洲
      value: "11"
    - text: TW/台湾
      value: "10"
    - text: HK/香港
      value: "9"
    - text: UK/英国
      value: "8"
    - text: US/美国
      value: "2"
    - text: CN/中国大陆
      value: "1"
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Other
      value: "35"
    - text: FraMeSToR
      value: "34"
    - text: EPSiLON
      value: "33"
    - text: BTN/NTb
      value: "32"
    - text: Hares
      value: "31"
    - text: Audiences
      value: "30"
    - text: PTHome
      value: "29"
    - text: HDHome
      value: "28"
    - text: LemonHD
      value: "27"
    - text: PTer
      value: "26"
    - text: OurBits
      value: "25"
    - text: HDS/HDSky
      value: "24"
    - text: FRDS
      value: "23"
    - text: CMCT
      value: "22"
    - text: beAst
      value: "21"
    - text: WiKi
      value: "5"
    - text: TTG
      value: "4"
    - text: HDC/HDChina
      value: "3"
    - text: CHD/CHDBits
      value: "2"
    - text: PTChina
      value: "1"
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: 中字
uplver:
  selector: input[name="uplver"]
  type: checkbox
  label: null
host: ptchina.org
uploadPath: /upload.php
```
