### ISSUE TITLE
[新站点]蟹黄堡

### ISSUE THREAD

**Issue by 616734202** [techmovie/easy-upload#341]
### 站点架构

NexusPHP

### 站点配置

```yaml
search:
  selector: input[name="search"]
  type: text
  label: null
search_area:
  selector: select[name="search_area"]
  options:
    - text: 标题
      value: "0"
    - text: 简介
      value: "1"
    - text: 发布者
      value: "3"
    - text: IMDB链接
      value: "4"
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
url: https://crabpt.vip
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 颜色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字体 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字号 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
technical_info:
  selector: textarea[name="technical_info"]
type:
  selector: select[name="type"]
  options:
    - text: 请选择
      value: "0"
    - text: 漫画 / Cartoon
      value: "415"
    - text: 游戏 / Game
      value: "414"
    - text: 学习 / Study
      value: "412"
    - text: 有声书 / Audiobook
      value: "411"
    - text: 电子书 / Ebook/
      value: "410"
"source_sel[4]":
  selector: select[name="source_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: CD
      value: "8"
    - text: HDTV
      value: "7"
    - text: WEB-DL
      value: "6"
    - text: Encode
      value: "5"
    - text: Remux
      value: "4"
    - text: UHD Blu-ray
      value: "3"
    - text: BluRay
      value: "2"
    - text: Other
      value: "1"
    - text: MVC
      value: "9"
    - text: ProRes
      value: "10"
    - text: Xvid
      value: "11"
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 8K
      value: "5"
    - text: 4K/2160p
      value: "4"
    - text: 1080p/1080i
      value: "3"
    - text: 720p
      value: "2"
    - text: Other
      value: "1"
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: AV1
      value: "6"
    - text: VP9
      value: "5"
    - text: H.266/VVC
      value: "4"
    - text: HEVC/H.265/x265
      value: "3"
    - text: AVC/H.264/x264
      value: "2"
    - text: Other
      value: "1"
    - text: VC-1
      value: "14"
    - text: MPEG
      value: "15"
"audiocodec_sel[4]":
  selector: select[name="audiocodec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: ALAC
      value: "16"
    - text: APE
      value: "12"
    - text: WAV
      value: "11"
    - text: FLAC
      value: "10"
    - text: MPEG
      value: "9"
    - text: DTS:X
      value: "8"
    - text: LPCM
      value: "7"
    - text: TrueHD
      value: "6"
    - text: DTS
      value: "5"
    - text: DDP/E-AC3
      value: "4"
    - text: DD/AC3
      value: "3"
    - text: AAC
      value: "2"
    - text: Other
      value: "1"
    - text: DTS-HD
      value: "15"
    - text: DTS-HD MA
      value: "17"
    - text: OGG
      value: "21"
    - text: DTS-HD
      value: "22"
    - text: DSD
      value: "23"
    - text: Opus
      value: "24"
    - text: Atmos
      value: "26"
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: AGSVWEB
      value: "15"
    - text: DYZ-WEB
      value: "11"
    - text: DYZ-Movie
      value: "12"
    - text: DYZ-TV
      value: "13"
    - text: UBits
      value: "9"
    - text: HHWEB
      value: "8"
    - text: FRDS
      value: "7"
    - text: XHB
      value: "6"
    - text: OurBits
      value: "5"
    - text: WiKi
      value: "4"
    - text: HDS
      value: "3"
    - text: CHD
      value: "2"
    - text: Other
      value: "1"
    - text: Audiences
      value: "10"
    - text: ZmWeb
      value: "16"
    - text: MTeam
      value: "37"
    - text: HDVWEB
      value: "36"
    - text: HDHome
      value: "35"
    - text: QHstudIo
      value: "34"
    - text: beAst
      value: "33"
    - text: tlf
      value: "32"
    - text: ZmWeb
      value: "31"
    - text: FROGWeb
      value: "30"
    - text: FROG
      value: "29"
    - text: FRDS
      value: "28"
    - text: CMCT
      value: "27"
    - text: WiKi
      value: "26"
    - text: ADWeb
      value: "25"
    - text: QHstudIo
      value: "24"
    - text: PiGoNF
      value: "23"
    - text: PigoWeb
      value: "22"
    - text: PigoHD
      value: "21"
    - text: HDFans
      value: "20"
    - text: UBWEB
      value: "19"
    - text: FFans
      value: "18"
    - text: Pter
      value: "17"
"processing_sel[4]":
  selector: select[name="processing_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 印度（India）
      value: "7"
    - text: 韩国（KR）
      value: "6"
    - text: 日本（JP）
      value: "5"
    - text: 欧美（EU/US）
      value: "4"
    - text: 港台（HK/TW）
      value: "3"
    - text: 中国大陆（CN）
      value: "2"
    - text: 其他（Other）
      value: "1"
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: 伦理
"codec_sel[6]":
  selector: select[name="codec_sel[6]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: EPUB/ZAW3/MOBI
      value: "13"
    - text: ZIP
      value: "12"
    - text: PDF
      value: "11"
    - text: MOBI
      value: "10"
    - text: AZW3
      value: "9"
    - text: EPUB
      value: "8"
    - text: TXT
      value: "7"
    - text: Other
      value: "1"
"audiocodec_sel[6]":
  selector: select[name="audiocodec_sel[6]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: OGG
      value: "14"
    - text: M4A
      value: "13"
    - text: AAC
      value: "2"
    - text: Other
      value: "1"
    - text: DTS-HD
      value: "15"
    - text: DTS-HD MA
      value: "17"
    - text: DSD
      value: "23"
    - text: Atmos
      value: "26"
"team_sel[6]":
  selector: select[name="team_sel[6]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: AGSVWEB
      value: "15"
    - text: DYZ-WEB
      value: "11"
    - text: DYZ-Movie
      value: "12"
    - text: DYZ-TV
      value: "13"
    - text: UBits
      value: "9"
    - text: HHWEB
      value: "8"
    - text: FRDS
      value: "7"
    - text: XHB
      value: "6"
    - text: OurBits
      value: "5"
    - text: WiKi
      value: "4"
    - text: HDS
      value: "3"
    - text: CHD
      value: "2"
    - text: Other
      value: "1"
    - text: Audiences
      value: "10"
    - text: ZmWeb
      value: "16"
    - text: beAst
      value: "33"
    - text: tlf
      value: "32"
    - text: ZmWeb
      value: "31"
    - text: FROGWeb
      value: "30"
    - text: FROG
      value: "29"
    - text: FRDS
      value: "28"
    - text: CMCT
      value: "27"
    - text: WiKi
      value: "26"
    - text: ADWeb
      value: "25"
    - text: QHstudIo
      value: "24"
    - text: PiGoNF
      value: "23"
    - text: PigoWeb
      value: "22"
    - text: PigoHD
      value: "21"
    - text: HDFans
      value: "20"
    - text: UBWEB
      value: "19"
    - text: FFans
      value: "18"
    - text: Pter
      value: "17"
"processing_sel[6]":
  selector: select[name="processing_sel[6]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 印度（India）
      value: "7"
    - text: 韩国（KR）
      value: "6"
    - text: 日本（JP）
      value: "5"
    - text: 欧美（EU/US）
      value: "4"
    - text: 港台（HK/TW）
      value: "3"
    - text: 中国大陆（CN）
      value: "2"
    - text: 其他（Other）
      value: "1"
"tags[6][]":
  selector: input[name="tags[6][]"]
  type: checkbox
  label: 条漫
host: crabpt.vip
uploadPath: /upload.php
```
