### ISSUE TITLE
[新站点]红豆包

### ISSUE THREAD

**Issue by 616734202** [techmovie/easy-upload#342]
### 站点架构

NexusPHP

### 站点配置

```yaml
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
pt_gen:
  selector: input[name="pt_gen"]
  type: text
  label: null
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
url: https://hdbao.cc
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 颜色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字体 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字号 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
technical_info:
  selector: textarea[name="technical_info"]
type:
  selector: select[name="type"]
  options:
    - text: 请选择
      value: "0"
    - text: Sports/赛事
      value: "407"
    - text: Movies/电影
      value: "401"
    - text: TV Series/电视剧
      value: "402"
    - text: Documentaries/纪录片
      value: "404"
    - text: TV Shows/综艺
      value: "403"
    - text: Misc/音乐
      value: "409"
    - text: Concert/演唱会
      value: "408"
    - text: Music Videos/音乐MV
      value: "406"
    - text: Animations/动漫&动画
      value: "405"
    - text: Tutorial/教程
      value: "410"
    - text: Others/其他
      value: "411"
"medium_sel[4]":
  selector: select[name="medium_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: UHD Blu-ray 原盘
      value: "1"
    - text: UHD Blu-ray DIY
      value: "2"
    - text: Blu-ray 原盘
      value: "3"
    - text: Blu-ray DIY
      value: "4"
    - text: REMUX
      value: "5"
    - text: Encode
      value: "6"
    - text: WEB-DL
      value: "7"
    - text: HDTV
      value: "8"
    - text: DVD/CD
      value: "12"
    - text: Other
      value: "13"
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 4K/2160p
      value: "5"
    - text: 1080p
      value: "8"
    - text: 1080i
      value: "2"
    - text: 720p
      value: "7"
    - text: SD
      value: "10"
    - text: Other
      value: "11"
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: H.264/AVC/x264
      value: "1"
    - text: H.265/HEVC/x265
      value: "7"
    - text: VC-1
      value: "2"
    - text: MPEG-4
      value: "9"
    - text: MPEG-2
      value: "4"
    - text: Xvid
      value: "3"
    - text: AV1
      value: "10"
    - text: Other
      value: "5"
"audiocodec_sel[4]":
  selector: select[name="audiocodec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: DTS:X
      value: "8"
    - text: TrueHD Atmos
      value: "9"
    - text: DTS-HD MA
      value: "11"
    - text: TrueHD
      value: "12"
    - text: LPCM
      value: "13"
    - text: DTS
      value: "3"
    - text: FLAC
      value: "15"
    - text: AAC
      value: "1"
    - text: DD/AC3
      value: "2"
    - text: MP3
      value: "4"
    - text: OGG
      value: "5"
    - text: APE
      value: "6"
    - text: Other
      value: "7"
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: HDBao
      value: "1"
    - text: HD4FANS
      value: "10"
    - text: CHD
      value: "2"
    - text: MySiLU
      value: "3"
    - text: WiKi
      value: "4"
    - text: HDC
      value: "6"
    - text: CMCT
      value: "7"
    - text: HDSky
      value: "8"
    - text: HHClub
      value: "9"
    - text: Other
      value: "5"
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: 禁转
uplver:
  selector: input[name="uplver"]
  type: checkbox
  label: null
host: hdbao.cc
uploadPath: /upload.php
```
