### ISSUE TITLE
[新站点]

### ISSUE THREAD

**Issue by danielcini91** [techmovie/easy-upload#348]
### 站点架构

NexusPHP

### 站点配置

```yaml
order_by:
  selector: input[name="order_by"]
  type: hidden
  label: null
searchstr:
  selector: input[name="searchstr"]
  type: text
  label: null
action:
  selector: input[name="action"]
  type: hidden
  label: null
search:
  selector: input[name="search"]
  type: text
  label: null
apikey:
  selector: input[name="apikey"]
  type: hidden
  label: null
file_input:
  selector: input[name="file_input"]
  type: file
  label: null
empty_group:
  selector: input[name="empty_group"]
  type: checkbox
  label: Upload Later?
type:
  selector: select[name="type"]
  options:
    - text: Games
      value: Games
    - text: Applications
      value: Applications
    - text: E-Books
      value: E-Books
    - text: OST
      value: OST
dont_check_rules:
  selector: input[name="dont_check_rules"]
  type: checkbox
  label:  Only check this option if your torrent is some kind of exception and
    should bypass automatic filetype checking.
platform:
  selector: select[name="platform"]
  options:
    - text: ---
      value: ""
    - text: Mac
      value: Mac
    - text: iOS
      value: iOS
    - text: Apple Bandai Pippin
      value: Apple Bandai Pippin
    - text: Apple II
      value: Apple II
    - text: Android
      value: Android
    - text: DOS
      value: DOS
    - text: Windows
      value: Windows
    - text: Xbox
      value: Xbox
    - text: Xbox 360
      value: Xbox 360
    - text: Game Boy
      value: Game Boy
    - text: Game Boy Advance
      value: Game Boy Advance
    - text: Game Boy Color
      value: Game Boy Color
    - text: NES
      value: NES
    - text: Nintendo 64
      value: Nintendo 64
    - text: Nintendo 3DS
      value: Nintendo 3DS
    - text: New Nintendo 3DS
      value: New Nintendo 3DS
    - text: Nintendo DS
      value: Nintendo DS
    - text: Nintendo GameCube
      value: Nintendo GameCube
    - text: Pokemon Mini
      value: Pokemon Mini
    - text: SNES
      value: SNES
    - text: Switch
      value: Switch
    - text: Virtual Boy
      value: Virtual Boy
    - text: Wii
      value: Wii
    - text: Wii U
      value: Wii U
    - text: PlayStation 1
      value: PlayStation 1
    - text: PlayStation 2
      value: PlayStation 2
    - text: PlayStation 3
      value: PlayStation 3
    - text: PlayStation 4
      value: PlayStation 4
    - text: PlayStation 5
      value: PlayStation 5
    - text: PlayStation Portable
      value: PlayStation Portable
    - text: PlayStation Vita
      value: PlayStation Vita
    - text: Dreamcast
      value: Dreamcast
    - text: Game Gear
      value: Game Gear
    - text: Master System
      value: Master System
    - text: Mega Drive
      value: Mega Drive
    - text: Pico
      value: Pico
    - text: Saturn
      value: Saturn
    - text: SG-1000
      value: SG-1000
    - text: Atari 2600
      value: Atari 2600
    - text: Atari 5200
      value: Atari 5200
    - text: Atari 7800
      value: Atari 7800
    - text: Atari Jaguar
      value: Atari Jaguar
    - text: Atari Lynx
      value: Atari Lynx
    - text: Atari ST
      value: Atari ST
    - text: Amstrad CPC
      value: Amstrad CPC
    - text: Bandai WonderSwan
      value: Bandai WonderSwan
    - text: Bandai WonderSwan Color
      value: Bandai WonderSwan Color
    - text: Apple Bandai Pippin
      value: Apple Bandai Pippin
    - text: Commodore 64
      value: Commodore 64
    - text: Commodore 128
      value: Commodore 128
    - text: Commodore Amiga
      value: Commodore Amiga
    - text: Amiga CD32
      value: Amiga CD32
    - text: Commodore Plus-4
      value: Commodore Plus-4
    - text: Commodore VIC-20
      value: Commodore VIC-20
    - text: NEC PC-98
      value: NEC PC-98
    - text: NEC PC-FX
      value: NEC PC-FX
    - text: NEC SuperGrafx
      value: NEC SuperGrafx
    - text: NEC TurboGrafx-16
      value: NEC TurboGrafx-16
    - text: ZX Spectrum
      value: ZX Spectrum
    - text: MSX
      value: MSX
    - text: MSX 2
      value: MSX 2
    - text: Game.com
      value: Game.com
    - text: Gizmondo
      value: Gizmondo
    - text: V.Smile
      value: V.Smile
    - text: CreatiVision
      value: CreatiVision
    - text: Board Game
      value: Board Game
    - text: Card Game
      value: Card Game
    - text: Miniature Wargames
      value: Miniature Wargames
    - text: Pen and Paper RPG
      value: Pen and Paper RPG
    - text: 3DO
      value: 3DO
    - text: Casio Loopy
      value: Casio Loopy
    - text: Casio PV-1000
      value: Casio PV-1000
    - text: Colecovision
      value: Colecovision
    - text: Emerson Arcadia 2001
      value: Emerson Arcadia 2001
    - text: Entex Adventure Vision
      value: Entex Adventure Vision
    - text: Epoch Super Casette Vision
      value: Epoch Super Casette Vision
    - text: Fairchild Channel F
      value: Fairchild Channel F
    - text: Funtech Super Acan
      value: Funtech Super Acan
    - text: GamePark GP32
      value: GamePark GP32
    - text: General Computer Vectrex
      value: General Computer Vectrex
    - text: Interactive DVD
      value: Interactive DVD
    - text: Linux
      value: Linux
    - text: Hartung Game Master
      value: Hartung Game Master
    - text: Magnavox-Phillips Odyssey
      value: Magnavox-Phillips Odyssey
    - text: Mattel Intellivision
      value: Mattel Intellivision
    - text: Memotech MTX
      value: Memotech MTX
    - text: Miles Gordon Sam Coupe
      value: Miles Gordon Sam Coupe
    - text: Nokia N-Gage
      value: Nokia N-Gage
    - text: Oculus Quest
      value: Oculus Quest
    - text: Ouya
      value: Ouya
    - text: Philips Videopac+
      value: Philips Videopac+
    - text: Philips CD-i
      value: Philips CD-i
    - text: Phone/PDA
      value: Phone/PDA
    - text: RCA Studio II
      value: RCA Studio II
    - text: Sharp X1
      value: Sharp X1
    - text: Sharp X68000
      value: Sharp X68000
    - text: SNK Neo Geo
      value: SNK Neo Geo
    - text: SNK Neo Geo Pocket
      value: SNK Neo Geo Pocket
    - text: Taito Type X
      value: Taito Type X
    - text: Tandy Color Computer
      value: Tandy Color Computer
    - text: Tangerine Oric
      value: Tangerine Oric
    - text: Thomson MO5
      value: Thomson MO5
    - text: Watara Supervision
      value: Watara Supervision
    - text: Retro - Other
      value: Retro - Other
importance:
  selector: input[name="importance"]
  type: hidden
  label: null
title:
  selector: input[name="title"]
  type: text
  label: null
aliases:
  selector: input[name="aliases"]
  type: text
  label: null
genre_tags:
  selector: select[name="genre_tags"]
  options:
    - text: ---
      value: ""
    - text: action
      value: action
    - text: adult
      value: adult
    - text: adventure
      value: adventure
    - text: ambient
      value: ambient
    - text: arcade
      value: arcade
    - text: casual
      value: casual
    - text: childrens
      value: childrens
    - text: electronic
      value: electronic
    - text: fantasy
      value: fantasy
    - text: fighting
      value: fighting
    - text: first.person.shooter
      value: first.person.shooter
    - text: horror
      value: horror
    - text: instrumental
      value: instrumental
    - text: mystery
      value: mystery
    - text: non.fiction
      value: non.fiction
    - text: platform
      value: platform
    - text: point.and.click
      value: point.and.click
    - text: puzzle
      value: puzzle
    - text: racing
      value: racing
    - text: role.playing.game
      value: role.playing.game
    - text: science.fiction
      value: science.fiction
    - text: shooter
      value: shooter
    - text: simulation
      value: simulation
    - text: sports
      value: sports
    - text: strategy
      value: strategy
    - text: survival
      value: survival
    - text: tactics
      value: tactics
    - text: turn.based.strategy
      value: turn.based.strategy
    - text: visual.novel
      value: visual.novel
    - text: vocal
      value: vocal
tags:
  selector: input[name="tags"]
  type: text
  label: null
year:
  selector: input[name="year"]
  type: number
  label: null
rating:
  selector: select[name="rating"]
  options:
    - text: ---
      value: ""
    - text: 3+
      value: "1"
    - text: 7+
      value: "3"
    - text: 12+
      value: "5"
    - text: 16+
      value: "7"
    - text: 18+
      value: "9"
    - text: N/A
      value: "13"
getPegi:
  selector: input[name="getPegi"]
  type: submit
  label: null
getIGDBESRB:
  selector: input[name="getIGDBESRB"]
  type: submit
  label: null
getIGDBPEGI:
  selector: input[name="getIGDBPEGI"]
  type: submit
  label: null
meta:
  selector: input[name="meta"]
  type: number
  label: null
metauri:
  selector: input[name="metauri"]
  type: url
  label: null
ignscore:
  selector: input[name="ignscore"]
  type: number
  label: null
ignuri:
  selector: input[name="ignuri"]
  type: url
  label: null
gamespotscore:
  selector: input[name="gamespotscore"]
  type: number
  label: null
gamespotscoreuri:
  selector: input[name="gamespotscoreuri"]
  type: url
  label: null
gameswebsiteuri:
  selector: input[name="gameswebsiteuri"]
  type: url
  label: null
wikipediauri:
  selector: input[name="wikipediauri"]
  type: url
  label: null
giantbomburi:
  selector: input[name="giantbomburi"]
  type: url
  label: null
image:
  selector: input[name="image"]
  type: url
  label: null
trailer:
  selector: input[name="trailer"]
  type: url
  label: null
getYT:
  selector: input[name="getYT"]
  type: submit
  label: null
album_desc:
  selector: textarea[name="album_desc"]
"screens[]":
  selector: input[name="screens[]"]
  type: text
  label: null
remaster:
  selector: input[name="remaster"]
  type: checkbox
  label: >-
    Is this torrent a special edition,
                                (GOG Edition, itch.io, Collectors or Platinum Edition, etc.)?
remaster_year:
  selector: input[name="remaster_year"]
  type: number
  label: null
remaster_title:
  selector: input[name="remaster_title"]
  type: text
  label: null
ripsrc:
  selector: input[name="ripsrc"]
  type: radio
  label: Other
release_title:
  selector: input[name="release_title"]
  type: text
  label: null
miscellaneous:
  selector: select[name="miscellaneous"]
  options:
    - text: ---
      value: ""
    - text: Full ISO
      value: Full ISO
    - text: GameDOX
      value: GameDOX
    - text: GGn Internal
      value: GGn Internal
    - text: P2P Full Repack
      value: P2P Full Repack
    - text: P2P Lossy Repack
      value: P2P Lossy Repack
    - text: P2P Release
      value: P2P Release
    - text: Rip
      value: Rip
    - text: Scrubbed
      value: Scrubbed
    - text: Home Rip
      value: Home Rip
    - text: DRM Free
      value: DRM Free
    - text: ROM
      value: ROM
    - text: E-Book
      value: E-Book
    - text: Other
      value: Other
gamedox:
  selector: select[name="gamedox"]
  options:
    - text: ---
      value: ""
    - text: Fix/Keygen
      value: Fix/Keygen
    - text: Update
      value: Update
    - text: DLC
      value: DLC
    - text: GOG-Goodies
      value: GOG-Goodies
    - text: Trainer
      value: Trainer
    - text: Tool
      value: Tool
    - text: Guide
      value: Guide
    - text: Artwork
      value: Artwork
    - text: Audio
      value: Audio
gamedoxvers:
  selector: input[name="gamedoxvers"]
  type: text
  label: null
format:
  selector: select[name="format"]
  options:
    - text: ---
      value: ""
    - text: PDF
      value: PDF
    - text: EPUB
      value: EPUB
    - text: MOBI
      value: MOBI
    - text: CBZ
      value: CBZ
    - text: CBR
      value: CBR
    - text: CB7
      value: CB7
    - text: AZW3
      value: AZW3
    - text: Other
      value: Other
scan:
  selector: input[name="scan"]
  type: radio
  label: Scan
scan_dpi:
  selector: select[name="scan_dpi"]
  options:
    - text: ---
      value: ""
    - text: "72"
      value: "72"
    - text: "96"
      value: "96"
    - text: "100"
      value: "100"
    - text: "150"
      value: "150"
    - text: "200"
      value: "200"
    - text: "250"
      value: "250"
    - text: "300"
      value: "300"
    - text: "400"
      value: "400"
    - text: "600"
      value: "600"
    - text: "1200"
      value: "1200"
    - text: Other
      value: Other
other_dpi:
  selector: input[name="other_dpi"]
  type: text
  label: null
scan_ocr:
  selector: input[name="scan_ocr"]
  type: checkbox
  label: Text is selectable.
isbn:
  selector: input[name="isbn"]
  type: text
  label: null
region:
  selector: select[name="region"]
  options:
    - text: ---
      value: ""
    - text: USA
      value: USA
    - text: Europe
      value: Europe
    - text: Japan
      value: Japan
    - text: Asia
      value: Asia
    - text: Australia
      value: Australia
    - text: France
      value: France
    - text: Germany
      value: Germany
    - text: Spain
      value: Spain
    - text: Italy
      value: Italy
    - text: UK
      value: UK
    - text: Netherlands
      value: Netherlands
    - text: Sweden
      value: Sweden
    - text: Russia
      value: Russia
    - text: China
      value: China
    - text: Korea
      value: Korea
    - text: Hong Kong
      value: Hong Kong
    - text: Taiwan
      value: Taiwan
    - text: Brazil
      value: Brazil
    - text: Canada
      value: Canada
    - text: Japan, USA
      value: Japan, USA
    - text: Japan, Europe
      value: Japan, Europe
    - text: USA, Europe
      value: USA, Europe
    - text: Europe, Australia
      value: Europe, Australia
    - text: Japan, Asia
      value: Japan, Asia
    - text: UK, Australia
      value: UK, Australia
    - text: World
      value: World
    - text: Region-Free
      value: Region-Free
    - text: Other
      value: Other
language:
  selector: select[name="language"]
  options:
    - text: ---
      value: ""
    - text: Multi-Language
      value: Multi-Language
    - text: English
      value: English
    - text: German
      value: German
    - text: French
      value: French
    - text: Czech
      value: Czech
    - text: Chinese
      value: Chinese
    - text: Italian
      value: Italian
    - text: Japanese
      value: Japanese
    - text: Korean
      value: Korean
    - text: Polish
      value: Polish
    - text: Portuguese
      value: Portuguese
    - text: Russian
      value: Russian
    - text: Spanish
      value: Spanish
    - text: Other
      value: Other
file_release_desc:
  selector: input[name="file_release_desc"]
  type: file
  label: null
release_desc:
  selector: textarea[name="release_desc"]
anonymous:
  selector: input[name="anonymous"]
  type: checkbox
  label: Anonymous
submit_upload:
  selector: input[name="submit_upload"]
  type: submit
  label: null
url: https://gazellegames.net
host: gazellegames.net
uploadPath: /upload.php
```
