### ISSUE TITLE
[新站点]垃圾桶

### ISSUE THREAD

**Issue by sqing33** [techmovie/easy-upload#350]
### 站点架构

NexusPHP

### 站点配置

```yaml
file:
  selector: input[name="file"]
  type: file
  label: null
name:
  selector: input[name="name"]
  type: text
  label: null
small_descr:
  selector: input[name="small_descr"]
  type: text
  label: null
url: https://pt.lajidui.top
nfo:
  selector: input[name="nfo"]
  type: file
  label: null
b:
  selector: input[name="b"]
  type: button
  label: null
i:
  selector: input[name="i"]
  type: button
  label: null
u:
  selector: input[name="u"]
  type: button
  label: null
IMG:
  selector: input[name="IMG"]
  type: button
  label: null
list:
  selector: input[name="list"]
  type: button
  label: null
quote:
  selector: input[name="quote"]
  type: button
  label: null
tagcount:
  selector: input[name="tagcount"]
  type: button
  label: null
color:
  selector: select[name="color"]
  options:
    - text: --- 颜色 ---
      value: "0"
    - text: Black
      value: Black
    - text: Sienna
      value: Sienna
    - text: Dark Olive Green
      value: DarkOliveGreen
    - text: Dark Green
      value: DarkGreen
    - text: Dark Slate Blue
      value: DarkSlateBlue
    - text: Navy
      value: Navy
    - text: Indigo
      value: Indigo
    - text: Dark Slate Gray
      value: DarkSlateGray
    - text: Dark Red
      value: DarkRed
    - text: Dark Orange
      value: DarkOrange
    - text: Olive
      value: Olive
    - text: Green
      value: Green
    - text: Teal
      value: Teal
    - text: Blue
      value: Blue
    - text: Slate Gray
      value: SlateGray
    - text: Dim Gray
      value: DimGray
    - text: Red
      value: Red
    - text: Sandy Brown
      value: SandyBrown
    - text: Yellow Green
      value: YellowGreen
    - text: Sea Green
      value: SeaGreen
    - text: Medium Turquoise
      value: MediumTurquoise
    - text: Royal Blue
      value: RoyalBlue
    - text: Purple
      value: Purple
    - text: Gray
      value: Gray
    - text: Magenta
      value: Magenta
    - text: Orange
      value: Orange
    - text: Yellow
      value: Yellow
    - text: Lime
      value: Lime
    - text: Cyan
      value: Cyan
    - text: Deep Sky Blue
      value: DeepSkyBlue
    - text: Dark Orchid
      value: DarkOrchid
    - text: Silver
      value: Silver
    - text: Pink
      value: Pink
    - text: Wheat
      value: Wheat
    - text: Lemon Chiffon
      value: LemonChiffon
    - text: Pale Green
      value: PaleGreen
    - text: Pale Turquoise
      value: PaleTurquoise
    - text: Light Blue
      value: LightBlue
    - text: Plum
      value: Plum
    - text: White
      value: White
font:
  selector: select[name="font"]
  options:
    - text: --- 字体 ---
      value: "0"
    - text: Arial
      value: Arial
    - text: Arial Black
      value: Arial Black
    - text: Arial Narrow
      value: Arial Narrow
    - text: Book Antiqua
      value: Book Antiqua
    - text: Century Gothic
      value: Century Gothic
    - text: Comic Sans MS
      value: Comic Sans MS
    - text: Courier New
      value: Courier New
    - text: Fixedsys
      value: Fixedsys
    - text: Garamond
      value: Garamond
    - text: Georgia
      value: Georgia
    - text: Impact
      value: Impact
    - text: Lucida Console
      value: Lucida Console
    - text: Lucida Sans Unicode
      value: Lucida Sans Unicode
    - text: Microsoft Sans Serif
      value: Microsoft Sans Serif
    - text: Palatino Linotype
      value: Palatino Linotype
    - text: System
      value: System
    - text: Tahoma
      value: Tahoma
    - text: Times New Roman
      value: Times New Roman
    - text: Trebuchet MS
      value: Trebuchet MS
    - text: Verdana
      value: Verdana
size:
  selector: select[name="size"]
  options:
    - text: --- 字号 ---
      value: "0"
    - text: "1"
      value: "1"
    - text: "2"
      value: "2"
    - text: "3"
      value: "3"
    - text: "4"
      value: "4"
    - text: "5"
      value: "5"
    - text: "6"
      value: "6"
    - text: "7"
      value: "7"
descr:
  selector: textarea[name="descr"]
technical_info:
  selector: textarea[name="technical_info"]
type:
  selector: select[name="type"]
  options:
    - text: 请选择
      value: "0"
    - text: Movies/电影
      value: "401"
    - text: TV Series/电视剧
      value: "402"
    - text: TV Shows/综艺
      value: "403"
    - text: Documentaries/纪录片
      value: "404"
    - text: Animations/动漫
      value: "405"
    - text: Music Videos/音乐视频
      value: "406"
    - text: Sports/体育
      value: "407"
    - text: Audio/音频
      value: "408"
    - text: Misc/其他
      value: "409"
    - text: Cartoon/少儿动画
      value: "410"
    - text: Ebook/电子书
      value: "411"
    - text: ShortDrama/短剧
      value: "412"
    - text: Game/游戏
      value: "413"
    - text: APP/软件
      value: "414"
    - text: Education/教育视频
      value: "415"
    - text: Audiobook/有声书
      value: "416"
"medium_sel[4]":
  selector: select[name="medium_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: WEB-DL
      value: "10"
    - text: Track
      value: "9"
    - text: CD
      value: "8"
    - text: DVDR
      value: "6"
    - text: HDTV
      value: "5"
    - text: MiniBD
      value: "4"
    - text: Encode
      value: "7"
    - text: Remux
      value: "3"
    - text: HD DVD
      value: "2"
    - text: Blu-ray
      value: "1"
    - text: Other
      value: "11"
"processing_sel[4]":
  selector: select[name="processing_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: MKV
      value: "10"
    - text: MP4
      value: "11"
    - text: EPUB
      value: "1"
    - text: PDF
      value: "2"
    - text: TXT
      value: "3"
    - text: DOCX
      value: "4"
    - text: PPTX
      value: "5"
    - text: XLSX
      value: "6"
    - text: WPS
      value: "7"
    - text: AZW3
      value: "8"
    - text: MOBI
      value: "9"
    - text: RAR
      value: "12"
    - text: ZIP
      value: "13"
    - text: 7z
      value: "14"
    - text: ISO
      value: "16"
    - text: Other
      value: "17"
"codec_sel[4]":
  selector: select[name="codec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: AV1
      value: "6"
    - text: H.265
      value: "7"
    - text: H.264
      value: "1"
    - text: VC-1
      value: "2"
    - text: Xvid
      value: "3"
    - text: MPEG-2
      value: "4"
    - text: Other
      value: "5"
"standard_sel[4]":
  selector: select[name="standard_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 8k
      value: "7"
    - text: 4k
      value: "6"
    - text: 2k
      value: "5"
    - text: 1080p
      value: "1"
    - text: 1080i
      value: "2"
    - text: 720p
      value: "3"
    - text: SD
      value: "4"
    - text: Other
      value: "8"
"audiocodec_sel[4]":
  selector: select[name="audiocodec_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: FLAC
      value: "1"
    - text: APE
      value: "2"
    - text: DTS
      value: "3"
    - text: MP3
      value: "4"
    - text: OGG
      value: "5"
    - text: AAC
      value: "6"
    - text: Other
      value: "7"
    - text: WAV
      value: "8"
    - text: DTS-HD
      value: "9"
    - text: TrueHD
      value: "10"
    - text: LPCM
      value: "11"
    - text: E-AC-3
      value: "12"
    - text: AC-3
      value: "13"
"source_sel[4]":
  selector: select[name="source_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: 大陆
      value: "7"
    - text: 台湾
      value: "2"
    - text: 香港
      value: "8"
    - text: 日本
      value: "10"
    - text: 韩国
      value: "11"
    - text: 欧美
      value: "1"
    - text: 印度
      value: "3"
    - text: Other
      value: "6"
"team_sel[4]":
  selector: select[name="team_sel[4]"]
  options:
    - text: 请选择一项
      value: "0"
    - text: Ourbits
      value: "12"
    - text: GodDramas
      value: "22"
    - text: BeiTai
      value: "21"
    - text: BMDru
      value: "20"
    - text: LHD
      value: "19"
    - text: beAst
      value: "18"
    - text: CatEDU
      value: "17"
    - text: Pter
      value: "16"
    - text: AGSVWEB
      value: "15"
    - text: HDHome
      value: "14"
    - text: QHstudIo
      value: "13"
    - text: HDSky
      value: "1"
    - text: UBits
      value: "11"
    - text: TJUPT
      value: "10"
    - text: FRDS
      value: "9"
    - text: CMCT
      value: "8"
    - text: ADE
      value: "7"
    - text: HHWEB
      value: "6"
    - text: Other
      value: "5"
    - text: WiKi
      value: "4"
    - text: 原创
      value: "3"
    - text: CHD
      value: "2"
"tags[4][]":
  selector: input[name="tags[4][]"]
  type: checkbox
  label: 完结
host: pt.lajidui.top
uploadPath: /upload.php
```
